### ISSUE TITLE
Screen is too small

### ISSUE THREAD

**Issue by Quessts** [NeuralNine/vidstream#1]
Hey so I've been experimenting with this module. It's honestly great but the screen sharing window is too small. Is their an option to maybe resize it? Make it bigger? Thanks in advance!

**Comment by Quessts** [comment]
Oh awesome. Thanks for answering I'm a big fan of your channel. Also one more thing. I'm building a program that can stream both live webcam footage and live screen sharing. I'm using sockets and in order to get the webcam to work (by using CV2) I need to bind the server with the client. But if I start using vidstream I get an error because I the port is already connected (from sockets and CV2).  So basically I was just wondering if I could bind vidstream with sockets as one so they work as one server. Many thanks in advance!

**Comment by NeuralNine** [comment]
vidstream handles all the camera interaction itself. You can write a script with a client and a server in it or even with two clients. But you cannot access the same camera twice.
