### ISSUE TITLE
PY Audio ERROR

### ISSUE THREAD

**Issue by VimKidCodez** [NeuralNine/vidstream#12]
I am not able to install this package because of pyaudio error...................

**Comment by jateute** [comment]
You can Download PyAudio [here](https://pypi.org/project/PyAudio/#files) .

**Comment by NeuralNine** [comment]
This issue doesn't contain any relevant information that is needed to solve the problem. Furthermore, it is a problem with PyAudio and not with vidstream, which means that this is not the right place to open such an issue.
