### ISSUE TITLE
Ubuntu installation have finished with error

### ISSUE THREAD

**Issue by alyhalo** [NeuralNine/vidstream#7]
There is an error with ubuntu installation using this command:

`pip3 install vidstream`

I got this output:

Collecting vidstream
  Downloading vidstream-0.0.14-py3-none-any.whl (8.0 kB)
Collecting opencv-python
  Downloading opencv_python-4.5.1.48-cp38-cp38-manylinux2014_x86_64.whl (50.4 MB)
     |████████████████████████████████| 50.4 MB 7.8 MB/s 
Collecting pyautogui
  Downloading PyAutoGUI-0.9.52.tar.gz (55 kB)
     |████████████████████████████████| 55 kB 4.2 MB/s 
Collecting pyaudio
  Downloading PyAudio-0.2.11.tar.gz (37 kB)
Requirement already satisfied: numpy>=1.17.3 in ./.local/lib/python3.8/site-packages (from opencv-python->vidstream) (1.18.0)
Collecting PyTweening>=1.0.1
  Downloading PyTweening-1.0.3.zip (15 kB)
Collecting mouseinfo
  Downloading MouseInfo-0.1.3.tar.gz (10 kB)
Collecting pygetwindow>=0.0.5
  Downloading PyGetWindow-0.0.9.tar.gz (9.7 kB)
Collecting pymsgbox
  Downloading PyMsgBox-1.0.9.tar.gz (18 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting pyscreeze>=0.1.21
  Downloading PyScreeze-0.1.27.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting python3-Xlib
  Downloading python3-xlib-0.15.tar.gz (132 kB)
     |████████████████████████████████| 132 kB 2.9 MB/s 
Collecting pyperclip
  Downloading pyperclip-1.8.2.tar.gz (20 kB)
Collecting pyrect
  Downloading PyRect-0.1.4.tar.gz (15 kB)
Requirement already satisfied: Pillow>=6.2.1; python_version == "3.8" in /usr/lib/python3/dist-packages (from pyscreeze>=0.1.21->pyautogui->vidstream) (7.0.0)
Building wheels for collected packages: pyautogui, pyaudio, PyTweening, mouseinfo, pygetwindow, pymsgbox, pyscreeze, python3-Xlib, pyperclip, pyrect
  Building wheel for pyautogui (setup.py) ... done
  Created wheel for pyautogui: filename=PyAutoGUI-0.9.52-py3-none-any.whl size=35194 sha256=2837293c96741f0f0b2fad8b73477867d446077687f97d36c83c39c43f22633d
  Stored in directory: /home/alyferryhalo/.cache/pip/wheels/4d/0d/6a/4258cb741835ea9ce7897652ae88272d3baf5cb1944c1984aa
  Building wheel for pyaudio (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c4urybjp/pyaudio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c4urybjp/pyaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-bljliv8d
       cwd: /tmp/pip-install-c4urybjp/pyaudio/
  Complete output (16 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  copying src/pyaudio.py -> build/lib.linux-x86_64-3.8
  running build_ext
  building '_portaudio' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/src
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -c src/_portaudiomodule.c -o build/temp.linux-x86_64-3.8/src/_portaudiomodule.o
  src/_portaudiomodule.c:29:10: fatal error: portaudio.h: No such file or directory
     29 | #include "portaudio.h"
        |          ^~~~~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyaudio
  Running setup.py clean for pyaudio
  Building wheel for PyTweening (setup.py) ... done
  Created wheel for PyTweening: filename=PyTweening-1.0.3-py3-none-any.whl size=3815 sha256=4e313c153b5275cc2ae128cb57bda63b5a1c4956c0cdcb8939615aca0452276d
  Stored in directory: /home/alyferryhalo/.cache/pip/wheels/e7/50/20/790fbd95739abfdf0348bef99d5cc0c7c2930a19a91f602ddc
  Building wheel for mouseinfo (setup.py) ... done
  Created wheel for mouseinfo: filename=MouseInfo-0.1.3-py3-none-any.whl size=10906 sha256=f9ee8e44d222001ec65d06f15870af5f73a7b4469bf717d361cb58abf9130614
  Stored in directory: /home/alyferryhalo/.cache/pip/wheels/d1/72/fb/35f403de66285df8ecca7049bcc61bfb57aba0f76d1f08f7eb
  Building wheel for pygetwindow (setup.py) ... done
  Created wheel for pygetwindow: filename=PyGetWindow-0.0.9-py3-none-any.whl size=11082 sha256=e17303e47a2887373dce782d4715be3502564cbeeec2d3414f0b35de2940508f
  Stored in directory: /home/alyferryhalo/.cache/pip/wheels/91/e3/04/184bda98ec7f7d5f0ba1f372bcf7b3ba86325151ae1dd690fe
  Building wheel for pymsgbox (PEP 517) ... done
  Created wheel for pymsgbox: filename=PyMsgBox-1.0.9-py3-none-any.whl size=7420 sha256=694e43383993f5baa56d1448d313d12f1a534e002f8c282ace2825911d685798
  Stored in directory: /home/alyferryhalo/.cache/pip/wheels/91/28/0d/f4eb606d38276836237d6dc2abf094241e6db5682a126e0389
  Building wheel for pyscreeze (PEP 517) ... done
  Created wheel for pyscreeze: filename=PyScreeze-0.1.27-py3-none-any.whl size=12864 sha256=05e42625d6ec6fde656b867feb05738e66c56d73856abba3c983b2f60219defa
  Stored in directory: /home/alyferryhalo/.cache/pip/wheels/f7/91/eb/c0fa176c095c77460a579ef339f24a377474b041e5543d1a00
  Building wheel for python3-Xlib (setup.py) ... done
  Created wheel for python3-Xlib: filename=python3_xlib-0.15-py3-none-any.whl size=109517 sha256=0859297f444517971f4e69fcdba47467d5d2af7317f47813cac6c279d35aa033
  Stored in directory: /home/alyferryhalo/.cache/pip/wheels/46/4e/a7/90774eeed70e4e93598bf4cbb1ef00c56e6bdc0fb99cc4215d
  Building wheel for pyperclip (setup.py) ... done
  Created wheel for pyperclip: filename=pyperclip-1.8.2-py3-none-any.whl size=11107 sha256=1191ecf648577bb1e43da2a7d277d509320d7b252d5eb3791da39fd7b1b60b8f
  Stored in directory: /home/alyferryhalo/.cache/pip/wheels/7f/1a/65/84ff8c386bec21fca6d220ea1f5498a0367883a78dd5ba6122
  Building wheel for pyrect (setup.py) ... done
  Created wheel for pyrect: filename=PyRect-0.1.4-py2.py3-none-any.whl size=9547 sha256=e7a98c5df0fe3fbd28b7afbef16d682527f3c69dfc5de53f392a2ee19ac771d8
  Stored in directory: /home/alyferryhalo/.cache/pip/wheels/d1/e4/47/c62f8291b16b6df7e89ac885881ff71f35ca04c6e384251de9
Successfully built pyautogui PyTweening mouseinfo pygetwindow pymsgbox pyscreeze python3-Xlib pyperclip pyrect
Failed to build pyaudio
Installing collected packages: opencv-python, PyTweening, pyperclip, python3-Xlib, mouseinfo, pyrect, pygetwindow, pymsgbox, pyscreeze, pyautogui, pyaudio, vidstream
    Running setup.py install for pyaudio ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c4urybjp/pyaudio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c4urybjp/pyaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-i93v236h/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/alyferryhalo/.local/include/python3.8/pyaudio
         cwd: /tmp/pip-install-c4urybjp/pyaudio/
    Complete output (16 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    copying src/pyaudio.py -> build/lib.linux-x86_64-3.8
    running build_ext
    building '_portaudio' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/src
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -c src/_portaudiomodule.c -o build/temp.linux-x86_64-3.8/src/_portaudiomodule.o
    src/_portaudiomodule.c:29:10: fatal error: portaudio.h: No such file or directory
       29 | #include "portaudio.h"
          |          ^~~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c4urybjp/pyaudio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c4urybjp/pyaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-i93v236h/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/alyferryhalo/.local/include/python3.8/pyaudio Check the logs for full command output.

So I use this:

- Ubuntu 20.04
- Python 3.8.5

How can I install vidstream?

**Comment by jateute** [comment]
You can download PyAudio with pipwin. You can download it with "pip install pipwin" and then you can Use "pipwin install pyaudio" to install PyAudio. After that you can download Vidstream again with pip.

**Comment by alyhalo** [comment]
Unfortunately, that does not work. After this command:

`pipwin install pyaudio`

I got this:

/home/alyferryhalo/.local/lib/python3.8/site-packages/pipwin/command.py:66: UserWarning: Found a non Windows system. Package installation might not work.
  warn("Found a non Windows system. Package installation might not work.")
Building cache. Hang on . . .
Done
Package `pyaudio` found in cache
Downloading package . . .
https://download.lfd.uci.edu/pythonlibs/w4tscw6k/PyAudio-0.2.11-cp38-cp38-win_amd64.whl
PyAudio-0.2.11-cp38-cp38-win_amd64.whl
 [*] 109 kB / 109 kB @ 17 kB/s [##################] [100%, 0s left]      
ERROR: PyAudio-0.2.11-cp38-cp38-win_amd64.whl is not a supported wheel on this platform.
Traceback (most recent call last):
  File "/home/alyferryhalo/.local/bin/pipwin", line 8, in <module>
    sys.exit(main())
  File "/home/alyferryhalo/.local/lib/python3.8/site-packages/pipwin/command.py", line 103, in main
    cache.install(package)
  File "/home/alyferryhalo/.local/lib/python3.8/site-packages/pipwin/pipwin.py", line 301, in install
    subprocess.check_call([executable, "-m", "pip", "install", wheel_file])
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', '/home/alyferryhalo/pipwin/PyAudio-0.2.11-cp38-cp38-win_amd64.whl']' returned non-zero exit status 1.

I suspect there is a problem with non-windows systems but thank you for help! I do want to believe that one day vidstream will be avaible for UNIX-syslems too.

**Comment by NeuralNine** [comment]
The problem you have is with the PyAudio installation and not with vidstream itself. The issue does not belong to this repository.
